title: "Xuanhao Cao"
author: "Xuanhao Cao"
description: "M.Sc. ML @ Uni Tübingen"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: flase           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md",  icon: universal-access, title:"Home", icon:home}
  - {file: "Blog.html", icon:file , title:"Blog"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: My Chinese Blog, icon: file-export, url: "https://www.zhihu.com/column/c_1613444881854255104"}
  - {title: Email, icon: envelope, url: "mailto:21xuanhao.cao@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/CaoXuanHao0"}
  - {title: Linkedin, icon: linkedin, url: "https://linkedin.com/in/xuanhao-cao-b22976242"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
